# -*- coding: utf-8 -*-
"""Dissertation_Kay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s80ytx_NVMqfw5t7zbTiVOupUpJgm9PR
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os
import xarray as xr
import matplotlib.pyplot as plt

from google.colab import drive

base_path = '/content/drive/MyDrive/Dissertation_Project'

folders = ['Temperature_flux', 'Precipitation_Flux', 'Solar_Flux']

for folder in folders:
    folder_path = os.path.join(base_path, folder)
    print(f"\nFiles in {folder}:")
    files = os.listdir(folder_path)
    print(files)

    nc_files = [f for f in files if f.endswith('.nc')]

    if nc_files:
        nc_path = os.path.join(folder_path, nc_files[0])
        print(f"\nOpening: {nc_path}")

        ds = xr.open_dataset(nc_path)
        display(ds)
    else:
        print("No .nc file found.")

def transform_climate(folder_name, output_name):
    folder_path = os.path.join(base_path, folder_name)

    nc_files = [
        os.path.join(folder_path, f)
        for f in os.listdir(folder_path)
        if f.endswith('.nc')
    ]

    all_data = []

    for file in nc_files:
        print(f"Processing {file}")

        ds = xr.open_dataset(file)
        df = ds.to_dataframe().reset_index()

        if 'crs' in df.columns:
            df = df.drop(columns=['crs'])

        climate_col = [c for c in df.columns if c not in ['time', 'lat', 'lon']][0]

        df['time'] = pd.to_datetime(df['time'])
        df['year'] = df['time'].dt.year

        yearly = df.groupby('year')[climate_col].mean().reset_index()
        yearly = yearly.rename(columns={climate_col: output_name})

        all_data.append(yearly)

    final_df = pd.concat(all_data).groupby('year').mean().reset_index()

    return final_df

!pip install xarray netCDF4 openpyxl h5netcdf

import pandas as pd
import xarray as xr
import glob
import os

from google.colab import drive
drive.mount('/content/drive')

yield_file = "/content/drive/MyDrive/Dissertation_Project/yield_dataset.xlsx"

temp_folder = "/content/drive/MyDrive/Dissertation_Project/Temperature_flux/"
precip_folder = "/content/drive/MyDrive/Dissertation_Project/Precipitation_flux/"
solar_folder = "/content/drive/MyDrive/Dissertation_Project/Solar_radiation_flux/"

from google.colab import drive
drive.mount('/content/drive')


import os

project_folder = "/content/drive/MyDrive/Dissertation_Project"
print(os.listdir(project_folder))


yield_file = "/content/drive/MyDrive/Dissertation_Project/final_model_dataset.csv"
yield_df = pd.read_csv(yield_file)


yield_df.head()

import os

project_folder = "/content/drive/MyDrive/Dissertation_Project"
print(os.listdir(project_folder))

import os

project_folder = "/content/drive/MyDrive/Dissertation_Project"
print(os.listdir(project_folder))

yield_file = "/content/drive/MyDrive/Dissertation_Project/yield_data.csv"

yield_df = pd.read_csv(yield_file)


yield_df.head()


print(yield_df.columns)

import pandas as pd


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)


yield_df

yield_df = yield_df[
    ['harvest_year', 'fertilizer_code', 'dry_matter_%', 'yield_100%dm']
].copy()


yield_df.columns = [
    'year',
    'fertilizer_code',
    'dry_matter',
    'yield'
]


yield_df.head()

print(yield_df.shape)
print(yield_df.columns)

import pandas as pd
import xarray as xr
import glob
import os
import re

def process_nc_folder(folder_path, climate_column, method="mean"):
    files = sorted(glob.glob(os.path.join(folder_path, "*.nc")))
    yearly_values = []

    for file in files:
        print("Processing:", os.path.basename(file))


        ds = xr.open_dataset(file, engine="h5netcdf")


        var_name = list(ds.data_vars.keys())[0]
        data = ds[var_name]

        if method == "mean":
            value = float(data.mean().values)
        elif method == "sum":
            value = float(data.sum().values)


        match = re.search(r"(\d{4})", os.path.basename(file))
        if match:
            year = int(match.group(1))
            yearly_values.append([year, value])

        ds.close()


    return pd.DataFrame(yearly_values, columns=["year", climate_column])

import pandas as pd
import xarray as xr
import glob
import os
import re

def process_nc_folder(folder_path, climate_column, method="mean"):
    files = sorted(glob.glob(os.path.join(folder_path, "*.nc")))
    yearly_values = []

    print(f"Found {len(files)} files in {folder_path}")

    for file in files:
        filename = os.path.basename(file)
        print(f"Processing: {filename}")

        try:

            ds = xr.open_dataset(file, engine="h5netcdf")


            var_name = list(ds.data_vars.keys())[0]
            data = ds[var_name]


            if method == "mean":
                value = float(data.mean(skipna=True).values)
            elif method == "sum":
                value = float(data.sum(skipna=True).values)
            else:
                raise ValueError("method must be 'mean' or 'sum'")


            match = re.search(r"(\d{4})", filename)
            if match:
                year = int(match.group(1))
                yearly_values.append([year, value])
                print(f"  ✓ Year {year}: {value}")
            else:
                print("  ⚠ Year not found in filename")

            ds.close()

        except Exception as e:

            print(f"  ✗ Skipped {filename}")
            print(f"    Error: {e}")
            continue


    result = pd.DataFrame(yearly_values, columns=["year", climate_column])


    result = result.drop_duplicates(subset="year").sort_values("year")

    print(f"\nCompleted: {len(result)} valid years extracted.")
    return result

temp_df = process_nc_folder(
    "/content/drive/MyDrive/Dissertation_Project/Temperature_flux/",
    "temperature",
    method="mean"
)

temp_df.head()

from google.colab import drive
drive.mount('/content/drive')

import os

parent_path = '/content/drive/MyDrive/Dissertation_Project'
directory_contents = os.listdir(parent_path)

temp_dir_name = None
for item in directory_contents:
    if item.strip() == 'Temperature': # Check if the item, when stripped, is 'Temperature'
        temp_dir_name = item
        break

if temp_dir_name:
    temp_path = os.path.join(parent_path, temp_dir_name)
    print(f"Attempting to list: {temp_path}")
    print(os.listdir(temp_path))
else:
    print(f"'Temperature' directory not found in {parent_path} after listing contents: {directory_contents}")

import pandas as pd
import xarray as xr
import glob
import os
import re

def process_nc_folder(folder_path, climate_column, method="mean"):
    # Search for .nc files in all subfolders
    files = sorted(glob.glob(os.path.join(folder_path, "**", "*.nc"), recursive=True))
    yearly_values = []

    print(f"Found {len(files)} files in {folder_path}")

    for file in files:
        filename = os.path.basename(file)
        print(f"Processing: {filename}")

        try:
            ds = xr.open_dataset(file, engine="h5netcdf")

            var_name = list(ds.data_vars.keys())[0]
            data = ds[var_name]

            if method == "mean":
                value = float(data.mean(skipna=True).values)
            elif method == "sum":
                value = float(data.sum(skipna=True).values)
            else:
                raise ValueError("method must be 'mean' or 'sum'")

            match = re.search(r"(\d{4})", filename)
            if match:
                year = int(match.group(1))
                yearly_values.append([year, value])

            ds.close()

        except Exception as e:
            print(f"Skipped {filename}: {e}")
            continue

    result = pd.DataFrame(yearly_values, columns=["year", climate_column])
    result = result.drop_duplicates(subset="year").sort_values("year")

    print(f"Completed: {len(result)} valid years extracted.")
    return result

import pandas as pd

df_temp = pd.read_csv('/content/drive/MyDrive/Dissertation_Project/df_temp_seasonal.csv')

import pandas as pd

df_temp = pd.read_csv('/content/drive/MyDrive/Dissertation_Project/df_temp_seasonal.csv')
df_temp.head()

import pandas as pd


final_old = pd.read_csv("/content/drive/MyDrive/Dissertation_Project/final_model_dataset.csv")


old_climate = final_old[
    ["year", "temperature", "precipitation", "solar_radiation"]
].drop_duplicates().sort_values("year")

old_climate.head()

import pandas as pd
import xarray as xr
import glob
import os
import re

def convert_daily_nc_to_yearly(folder_path, climate_column, method="mean"):
    files = sorted(glob.glob(os.path.join(folder_path, "**", "*.nc"), recursive=True))
    records = []

    print("Files found:", len(files))

    for file in files:
        filename = os.path.basename(file)

        try:
            ds = xr.open_dataset(file)

            var_name = list(ds.data_vars.keys())[0]
            data = ds[var_name]


            spatial_dims = [
                d for d in data.dims
                if d.lower() in ["lat", "latitude", "lon", "longitude"]
            ]

            if spatial_dims:
                daily_value = float(data.mean(dim=spatial_dims, skipna=True).values)
            else:
                daily_value = float(data.mean(skipna=True).values)


            match = re.search(r"(\d{4})", filename)
            if match:
                year = int(match.group(1))
                records.append([year, daily_value])

            ds.close()

        except Exception as e:
            print("Skipped:", filename, "|", e)

    daily_df = pd.DataFrame(records, columns=["year", "daily_value"])

    if method == "mean":
        yearly_df = daily_df.groupby("year")["daily_value"].mean().reset_index()
    elif method == "sum":
        yearly_df = daily_df.groupby("year")["daily_value"].sum().reset_index()

    yearly_df.columns = ["year", climate_column]
    return yearly_df

df_model = pd.read_csv('/content/drive/MyDrive/Dissertation_Project/final_model_dataset.csv')

df_model.head()

print("Rows and columns:", df_model.shape)
print(df_model.columns)

df_model.info()

df_model.isnull().sum()

df_model[['yield', 'temperature', 'precipitation', 'solar_radiation', 'dry_matter']].describe()

df_model['fertilizer_code'].value_counts()

plt.hist(df_model['yield'], bins=20)
plt.title('Distribution of Maize Yield')
plt.xlabel('Yield')
plt.ylabel('Frequency')
plt.show()

X = pd.get_dummies(
    df_model[['temperature', 'precipitation', 'solar_radiation', 'dry_matter', 'fertilizer_code']]
)

df_encoded = pd.get_dummies(df_model, columns=['fertilizer_code'], drop_first=True)

df_encoded.head()

corr = df_model[['yield', 'temperature', 'precipitation', 'solar_radiation', 'dry_matter']].corr()
print(corr)

import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Between Variables')
plt.show()

df_fert = df_model.groupby('fertilizer_code')['yield'].mean().sort_values(ascending=False)

top10 = df_fert.head(10)

plt.figure(figsize=(10,5))
top10.plot(kind='bar')

plt.title('Top 10 Fertilizer Treatments by Average Yield')
plt.xlabel('Fertilizer Type')
plt.ylabel('Average Yield')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,8))
df_fert.head(15).plot(kind='barh')

plt.title('Top Fertilizer Treatments by Yield')
plt.xlabel('Average Yield')
plt.ylabel('Fertilizer')
plt.tight_layout()
plt.show()

X = pd.get_dummies(
    df_model[['temperature', 'precipitation', 'solar_radiation', 'dry_matter', 'fertilizer_code']]
)

y = df_model['yield']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Linear Regression R²:", r2_score(y_test, y_pred_lr))
print("Linear Regression RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=300, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest R²:", r2_score(y_test, y_pred_rf))
print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

from xgboost import XGBRegressor


X_train_xgb = X_train.copy()
X_test_xgb = X_test.copy()

X_train_xgb.columns = X_train_xgb.columns.astype(str).str.replace('[', '', regex=False)\
                                             .str.replace(']', '', regex=False)\
                                             .str.replace('<', '', regex=False)

X_test_xgb.columns = X_test_xgb.columns.astype(str).str.replace('[', '', regex=False)\
                                           .str.replace(']', '', regex=False)\
                                           .str.replace('<', '', regex=False)

xgb = XGBRegressor(random_state=42)
xgb.fit(X_train_xgb, y_train)

y_pred_xgb = xgb.predict(X_test_xgb)

print("XGBoost R²:", r2_score(y_test, y_pred_xgb))
print("XGBoost RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

svr = Pipeline([
    ('scaler', StandardScaler()),
    ('svr', SVR())
])

svr.fit(X_train, y_train)

y_pred_svr = svr.predict(X_test)

print("SVR R²:", r2_score(y_test, y_pred_svr))
print("SVR RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_svr)))

results = pd.DataFrame({
    'Model': ['Linear Regression', 'Random Forest', 'XGBoost', 'SVR'],
    'R²': [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_rf),
        r2_score(y_test, y_pred_xgb),
        r2_score(y_test, y_pred_svr)
    ],
    'RMSE': [
        np.sqrt(mean_squared_error(y_test, y_pred_lr)),
        np.sqrt(mean_squared_error(y_test, y_pred_rf)),
        np.sqrt(mean_squared_error(y_test, y_pred_xgb)),
        np.sqrt(mean_squared_error(y_test, y_pred_svr))
    ]
})

results

import re
import numpy as np
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor


X_cv = X.copy()


X_cv.columns = [
    re.sub(r'[\[\]<>]', '', str(col)).replace(" ", "_")
    for col in X_cv.columns
]


X_cv = X_cv.astype(float)

xgb_cv = XGBRegressor(random_state=42)


cv_scores = cross_val_score(
    xgb_cv,
    X_cv,
    y,
    cv=5,
    scoring='r2'
)

print("Cross-validation R² scores:", cv_scores)
print("Average CV R²:", np.mean(cv_scores))

import re
import numpy as np
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor


X_tuned = X.copy()


X_tuned.columns = [
    re.sub(r'[\[\]<>]', '', str(col)).replace(" ", "_")
    for col in X_tuned.columns
]


X_tuned = X_tuned.astype(float)


xgb = XGBRegressor(
    objective='reg:squarederror',
    random_state=42
)


param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}


grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='r2',
    cv=5,
    n_jobs=-1,
    verbose=1
)


grid_search.fit(X_tuned, y)

print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validation R²:", grid_search.best_score_)

Q1 = y.quantile(0.25)
Q3 = y.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

mask = (y >= lower_bound) & (y <= upper_bound)

X_no_outliers = X_tuned[mask]
y_no_outliers = y[mask]

print("Original rows:", len(y))
print("Rows after removing outliers:", len(y_no_outliers))

from xgboost import XGBRegressor
from sklearn.model_selection import RepeatedKFold, cross_val_score


best_xgb = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42
)


rkf = RepeatedKFold(
    n_splits=5,
    n_repeats=10,
    random_state=42
)


scores = cross_val_score(
    best_xgb,
    X_tuned,
    y,
    cv=rkf,
    scoring='r2',
    n_jobs=-1
)

print("Repeated CV Mean R²:", round(scores.mean(), 4))
print("Repeated CV Std:", round(scores.std(), 4))

import pandas as pd
import matplotlib.pyplot as plt
import re
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor


df_model = pd.read_csv('/content/drive/MyDrive/Dissertation_Project/final_model_dataset.csv')


df_encoded = pd.get_dummies(df_model, columns=['fertilizer_code'], drop_first=True)


df_encoded.columns = [
    re.sub(r'[\[\]<>]', '', str(col)).replace(" ", "_")
    for col in df_encoded.columns
]


X = df_encoded.drop('yield', axis=1)
y = df_encoded['yield']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)


xgb_model = XGBRegressor(random_state=42)
xgb_model.fit(X_train, y_train)


y_pred = xgb_model.predict(X_test)


plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.7)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    linestyle='--'
)

plt.xlabel("Actual Yield")
plt.ylabel("Predicted Yield")
plt.title("Actual vs Predicted Maize Yield")
plt.show()

X_train_xgb = X_train_xgb.astype(float)
X_test_xgb = X_test_xgb.astype(float)

!pip install shap

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os
import xarray as xr
import matplotlib.pyplot as plt

from google.colab import drive

!pip install shap lime

# Install required libraries
!pip install shap lime

# Import libraries
import pandas as pd
import numpy as np
import shap
import lime

import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file == 'final_model_dataset.csv':
            print('FOUND:', os.path.join(root, file))

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Dissertation_Project/final_model_dataset.csv')

print("Dataset loaded successfully")
print(df.shape)
df.head()

from sklearn.model_selection import train_test_split

# Features
X = df.drop('yield', axis=1)

# Target
y = df['yield']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Train and test sets created successfully")
print(X_train.shape)
print(X_test.shape)

X = pd.get_dummies(X, columns=['fertilizer_code'], drop_first=False)


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.columns)

# Remove 'year' from the feature set
X = df.drop(['yield', 'year'], axis=1)

# Split the data again
from sklearn.model_selection import train_test_split

y = df['yield']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Year removed successfully.")
print(X.columns)

# Re-run your SHAP code after this step

y = df['yield']

X = df.drop(['yield', 'year'], axis=1)


X = pd.get_dummies(X, columns=['fertilizer_code'], drop_first=False)

print(X.columns)

y = df['yield']


X = df.drop(['yield', 'year'], axis=1)

X = pd.get_dummies(X, columns=['fertilizer_code'], drop_first=False)

print(X.columns)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

import re
import shap
import pandas as pd
import numpy as np
from xgboost import XGBRegressor


X_train_xgb = X_train.copy()
X_test_xgb = X_test.copy()


X_train_xgb = X_train_xgb.drop('year', axis=1, errors='ignore')
X_test_xgb = X_test_xgb.drop('year', axis=1, errors='ignore')


clean_columns = [
    re.sub(r'[\[\]<>]', '', str(col)).replace(" ", "_")
    for col in X_train_xgb.columns
]

X_train_xgb.columns = clean_columns
X_test_xgb.columns = clean_columns


X_train_xgb = X_train_xgb.apply(pd.to_numeric, errors='coerce').fillna(0)
X_test_xgb = X_test_xgb.apply(pd.to_numeric, errors='coerce').fillna(0)


xgb = XGBRegressor(random_state=42)
xgb.fit(X_train_xgb, y_train)


explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test_xgb)


shap.summary_plot(shap_values, X_test_xgb, max_display=20)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm


mean_shap = np.abs(shap_values).mean(axis=0)


importance_df = pd.DataFrame({
    'Feature': X_test_xgb.columns,
    'Mean_SHAP': mean_shap
})


importance_df = importance_df.sort_values('Mean_SHAP', ascending=False)


topk = importance_df.head(10)


colors = cm.viridis(np.linspace(1, 0, len(topk)))


plt.figure(figsize=(10, 6))
plt.barh(topk["Feature"], topk["Mean_SHAP"], color=colors)

plt.xlabel("Mean |SHAP value| (average impact on model output magnitude)")
plt.title("SHAP Feature Importance")


plt.gca().invert_yaxis()


plt.tight_layout()


plt.savefig("shap_feature_importance_top10.png", dpi=300, bbox_inches="tight")

plt.show()

!pip install lime

import matplotlib.pyplot as plt
import pandas as pd


lime_farmer_insight = pd.DataFrame({
    'Factor': [
        'High dry matter',
        'N1 fertilizer',
        'N4 fertilizer',
        'PKMg fertilizer',
        'Low precipitation',
        'FYM fertilizer'
    ],
    'Contribution': [3.84, 4.46, 4.03, 3.59, -1.28, -2.78]
})


colors = ['green' if x > 0 else 'red' for x in lime_farmer_insight['Contribution']]

plt.figure(figsize=(10, 6))

bars = plt.barh(
    lime_farmer_insight['Factor'],
    lime_farmer_insight['Contribution'],
    color=colors
)


for bar in bars:
    width = bar.get_width()
    plt.text(
        width + (0.1 if width > 0 else -0.5),
        bar.get_y() + bar.get_height()/2,
        f'{width:.2f}',
        va='center'
    )

plt.axvline(0)

plt.xlabel('Impact on Predicted Yield')
plt.ylabel('Factors')
plt.title('LIME Explanation (Farmer-Friendly) – Predicted Yield = 16.48')

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


lime_avg_df = pd.DataFrame({
    'Feature': [
        'fertilizer_code_(P)KMg <= 0.00',
        'fertilizer_code_Nil <= 0.00',
        'fertilizer_code_N4 <= 0.00',
        'fertilizer_code_N4PMg <= 0.00',
        'precipitation <= 396.50',
        'fertilizer_code_FYM_N3 <= 0.00'
    ],
    'Contribution': [4.18, 4.16, 3.83, 2.42, -1.14, -2.81]
})


colors = ['green' if x > 0 else 'red' for x in lime_avg_df['Contribution']]


plt.figure(figsize=(10, 6))


bars = plt.barh(
    lime_avg_df['Feature'],
    lime_avg_df['Contribution'],
    color=colors,
    label='XGBoost'
)


for bar in bars:
    width = bar.get_width()
    plt.text(
        width + (0.08 if width > 0 else -0.15),
        bar.get_y() + bar.get_height() / 2,
        f'{width:.2f}',
        va='center',
        ha='left' if width > 0 else 'right'
    )


plt.axvline(0, color='black', linewidth=1)


plt.xlabel('Impact on Predicted Yield')
plt.ylabel('Features')
plt.title('LIME Explanation - Average Yield Prediction (XGBoost)')


plt.legend()


plt.gca().invert_yaxis()


plt.xlim(-3.5, 4.7)


plt.tight_layout()
plt.savefig('lime_average_yield_prediction_xgboost.png', dpi=300, bbox_inches='tight')


plt.show()

import pandas as pd
import matplotlib.pyplot as plt

lime_low_df = pd.DataFrame({
    'Feature': [
        'fertilizer_code_Nil <= 0.00',
        'fertilizer_code_N4 <= 0.00',
        'fertilizer_code_N4PMg <= 0.00',
        'fertilizer_code_FYM_N3 <= 0.00',
        'dry_matter <= 22.80',
        'fertilizer_code__P_KMg > 0.00'
    ],
    'Contribution': [4.20, 3.96, 2.52, -2.78, -2.92, -4.19]
})


colors = ['green' if x > 0 else 'red' for x in lime_low_df['Contribution']]


plt.figure(figsize=(10, 6))


bars = plt.barh(
    lime_low_df['Feature'],
    lime_low_df['Contribution'],
    color=colors,
    label='XGBoost'
)


for bar in bars:
    width = bar.get_width()
    plt.text(
        width + (0.08 if width > 0 else -0.15),
        bar.get_y() + bar.get_height() / 2,
        f'{width:.2f}',
        va='center',
        ha='left' if width > 0 else 'right'
    )


plt.axvline(0, color='black', linewidth=1)


plt.xlabel('Impact on Predicted Yield')
plt.ylabel('Features')
plt.title('LIME Explanation - Low Yield Prediction (XGBoost)')


plt.legend()


plt.gca().invert_yaxis()


plt.xlim(-4.5, 4.6)


plt.tight_layout()
plt.savefig('lime_low_yield_prediction_xgboost.png', dpi=300, bbox_inches='tight')


plt.show()

import pandas as pd
import matplotlib.pyplot as plt

lime_high_df = pd.DataFrame({
    'Feature': [
        'fertilizer_code__P_KMg <= 0.00',
        'fertilizer_code_Nil <= 0.00',
        'dry_matter > 28.73',
        'fertilizer_code_N4 <= 0.00',
        'fertilizer_code_N4PMg <= 0.00',
        'precipitation <= 396.50'
    ],
    'Contribution': [4.47, 4.39, 4.36, 4.02, 2.71, -1.18]
})


colors = ['green' if x > 0 else 'red' for x in lime_high_df['Contribution']]


plt.figure(figsize=(10, 6))


bars = plt.barh(
    lime_high_df['Feature'],
    lime_high_df['Contribution'],
    color=colors,
    label='XGBoost'
)


for bar in bars:
    width = bar.get_width()
    plt.text(
        width + (0.08 if width > 0 else -0.15),
        bar.get_y() + bar.get_height() / 2,
        f'{width:.2f}',
        va='center',
        ha='left' if width > 0 else 'right'
    )


plt.axvline(0, color='black', linewidth=1)


plt.xlabel('Impact on Predicted Yield')
plt.ylabel('Features')
plt.title('LIME Explanation - High Yield Prediction (XGBoost)')


plt.legend()


plt.gca().invert_yaxis()


plt.xlim(-1.4, 4.8)


plt.tight_layout()
plt.savefig('lime_high_yield_prediction_xgboost.png', dpi=300, bbox_inches='tight')


plt.show()